steps:
  # 1 & 2. Fetch the secret and build the Docker image in one bash script
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        MONGO_URI=$(gcloud secrets versions access latest --secret=MONGODB_URI --format='get(payload.data)' | tr '_-' '/+' | base64 -d)
        echo "Mongo URI retrieved"
        docker build -t gcr.io/$PROJECT_ID/next-exp:$COMMIT_SHA --build-arg MONGODB_URI="$MONGO_URI" .

  # 3. Push the Docker image to Artifact/Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/next-exp:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
