steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
      '-c',
      'docker build --build-arg MONGODB_URL=$$MONGODB_URL -t my-image .'
    ]
    secretEnv: ['MONGODB_URL']

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/next-exp:$COMMIT_SHA

availableSecrets:
  secretManager:
  - versionName: projects/710919758521/secrets/MONGODB_URI/latest
    env: 'MONGODB_URL'

  # 3. Push the Docker image to Artifact/Container Registry


options:
  logging: CLOUD_LOGGING_ONLY
