steps:
   - name: 'gcr.io/cloud-builders/npm'
     entrypoint: 'bash'
     args:
       - '-c'
       - |
         npm install
         npm run build
     env:
       - NODE_ENV=production
       - NEXTAUTH_URL=https://localhost:3000
     secretEnv: ['MONGODB_URI', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'NEXTAUTH_SECRET']
availableSecrets:
  secretManager:
    - versionName: 'projects/your-project-id/secrets/MONGODB_URI/versions/latest'
      env: 'MONGODB_URI'
    - versionName: 'projects/your-project-id/secrets/GOOGLE_CLIENT_ID/versions/latest'
      env: 'GOOGLE_CLIENT_ID'
    - versionName: 'projects/your-project-id/secrets/GOOGLE_CLIENT_SECRET/versions/latest'
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: 'projects/your-project-id/secrets/NEXTAUTH_SECRET/versions/latest'
      env: 'NEXTAUTH_SECRET'


  