steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
      '-c',
      'docker build --build-arg MONGODB_URI=$$MONGODB_URI -t gcr.io/$PROJECT_ID/next-exp:$COMMIT_SHA .'
    ]
    secretEnv: ['MONGODB_URI']

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/next-exp:$COMMIT_SHA

availableSecrets:
  secretManager:
  - versionName: projects/710919758521/secrets/MONGODB_URI/versions/latest
    env: MONGODB_URI

  # 3. Push the Docker image to Artifact/Container Registry


options:
  logging: CLOUD_LOGGING_ONLY
