steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'fetch-secret'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Fetching MongoDB URI..."
      MONGO_URI=$(gcloud secrets versions access latest --secret=MONGODB_URI)
      echo "MONGO_URI=$MONGO_URI" > /workspace/.env

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build', '-t', 'gcr.io/$PROJECT_ID/nextjs-expense-tracker',
      '--build-arg', 'MONGODB_URI=$(grep MONGO_URI /workspace/.env | cut -d "=" -f2-)',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nextjs-expense-tracker']