steps:
   - name: 'gcr.io/cloud-builders/npm'
     entrypoint: 'bash'
     args:
       - '-c'
       - |
         export MONGODB_URI=$$MONGODB_URI
         export GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID
         export GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET
         export NEXTAUTH_SECRET=$$NEXTAUTH_SECRET
        
         npm install
         npm run build
     secretEnv: ['MONGODB_URI', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'NEXTAUTH_SECRET']
     env:
       - NODE_ENV=production
       - NEXTAUTH_URL=https://localhost:3000
   - name: 'gcr.io/cloud-builders/docker'
     args:
      - 'build'
      - '-t'
      - 'gcr.io/710919758521/nextjs-expense-tracker:$SHORT_SHA'
      - '--build-arg'
      - 'MONGODB_URI=$$MONGODB_URI'
      - '--build-arg'
      - 'GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID'
      - '--build-arg'
      - '--build-arg'
      - 'GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET'
      - '--build-arg'
      - 'NEXTAUTH_SECRET=$$NEXTAUTH_SECRET'
      - '.'
     env:
       - NODE_ENV=production
       - NEXTAUTH_URL=https://localhost:3000
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/710919758521/nextjs-expense-tracker:$SHORT_SHA']
images: ['gcr.io/710919758521/nextjs-expense-tracker:$SHORT_SHA']
availableSecrets:
  secretManager:
    - versionName: 'projects/710919758521/secrets/MONGODB_URI/versions/latest'
      env: 'MONGODB_URI'
    - versionName: 'projects/710919758521/secrets/GOOGLE_CLIENT_ID/versions/latest'
      env: 'GOOGLE_CLIENT_ID'
    - versionName: 'projects/710919758521/secrets/GOOGLE_CLIENT_SECRET/versions/latest'
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: 'projects/710919758521/secrets/NEXTAUTH_SECRET/versions/latest'
      env: 'NEXTAUTH_SECRET'


  