steps:
	- name: 'gcr.io/cloud-builders/docker'
  	entrypoint: 'bash'
  	args: [
    	'-c',
    	'docker build --build-arg MY_SECRET_ARG=$$MONGODB_URL -t my-image .'
    ]
  	secretEnv: ['MONGODB_URL']
	 
availableSecrets:
  secretManager:
  - versionName: projects/710919758521/secrets/MONGODB_URI/versions/2
    env: 'MONGODB_URL'

  # 3. Push the Docker image to Artifact/Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/next-exp:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
