import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import SignOutButton from "@/components/SignoutButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/api/auth/signin"); // Will redirect to Google sign-in
  }

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#10b981" />
        <link rel="icon" href="/icons/courthouse.png" />
        <link rel="apple-touch-icon" href="/icons/courthouse.png" />
      </head>
      <body className="bg-white text-gray-800">
      {/* Render only after session validation */}
      {session && (
          <>
       {/* Title Bar */}
        <header className="w-full bg-gray-600 text-white px-6 py-4 shadow">
            <div className="max-w-6xl mx-auto flex justify-between items-center">
              <h1 className="text-2xl font-bold">Expense Tracker</h1>
              <nav className="space-x-4 hidden sm:block">
                <a href="/transactions" className="hover:underline">
                  Transactions
                </a>
                <a href="/categories" className="hover:underline">
                  Categories
                </a>
              </nav>
              
            </div>
          </header>

          <main className="min-h-full p-4">{children}</main>
          </>
        )}
        
        <footer className="w-full bg-gray-600 text-white px-6 py-2 mt-auto fixed bottom-0 left-0">
            <div className="max-w-6xl mx-auto flex justify-between items-center">
          <p>&copy; {new Date().getFullYear()} Expense Tracker</p>
          <SignOutButton />
            </div>
        </footer>
      </body>
    </html>
  );
}
